name: test_nucleo
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
jobs:
  test_nucleo:
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 1
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive
      - name: Test with tox
        id: run-tox
        run: tox -vv
        env:
          PLATFORM: ${{ matrix.platform }}